
language: node_js
node_js:
  - '0.10'
before_install:
  - npm install -g grunt-cli
  - npm -g install npm@latest-2
notifications:
  email:
    on_success: change
    sudo: false
cache:
    directories:
        - node_modules
